version: '2'
services:
    guesswhat-app:
        image: guesswhat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://guesswhat-mariadb:3306/guesswhat
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    guesswhat-mariadb:
        extends:
            file: mariadb.yml
            service: guesswhat-mariadb
